name: Run Postman API Tests

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Install Newman & HTMLExtra reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: 🚀 Run Newman with HTMLExtra report
        run: |
          newman run "Books API Collection_Naorin.json" \
            -e "Books Collection Env_Naorin.json" \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/newman-report.html \
            --reporter-htmlextra-title "Books API Test Report" \
            --reporter-htmlextra-darkTheme \
            --reporter-htmlextra-showEnvironmentData

      - name: 📤 Upload Newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/newman-report.html
